FROM onsdigital/dp-concourse-tools-ubuntu-20:ubuntu20.4-rc.1

RUN apt-get update && apt-get install tzdata

WORKDIR /app/

COPY dp-frontend-homepage-controller .

CMD ./dp-frontend-homepage-controller
