// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package homepage

import (
	"context"
	"github.com/ONSdigital/dp-frontend-homepage-controller/model"
	"github.com/ONSdigital/dp-topic-api/models"
	"sync"
	"time"
)

var (
	lockHomepageClienterMockAddNavigationCache    sync.RWMutex
	lockHomepageClienterMockClose                 sync.RWMutex
	lockHomepageClienterMockGetHomePage           sync.RWMutex
	lockHomepageClienterMockGetNavigationData     sync.RWMutex
	lockHomepageClienterMockStartBackgroundUpdate sync.RWMutex
)

// Ensure, that HomepageClienterMock does implement Clienter.
// If this is not the case, regenerate this file with moq.
var _ Clienter = &HomepageClienterMock{}

// HomepageClienterMock is a mock implementation of Clienter.
//
//     func TestSomethingThatUsesHomepageClienter(t *testing.T) {
//
//         // make and configure a mocked Clienter
//         mockedHomepageClienter := &HomepageClienterMock{
//             AddNavigationCacheFunc: func(ctx context.Context, updateInterval time.Duration) error {
// 	               panic("mock out the AddNavigationCache method")
//             },
//             CloseFunc: func()  {
// 	               panic("mock out the Close method")
//             },
//             GetHomePageFunc: func(ctx context.Context, userAccessToken string, collectionID string, lang string) (*model.HomepageData, error) {
// 	               panic("mock out the GetHomePage method")
//             },
//             GetNavigationDataFunc: func(ctx context.Context, lang string) (*models.Navigation, error) {
// 	               panic("mock out the GetNavigationData method")
//             },
//             StartBackgroundUpdateFunc: func(ctx context.Context, errorChannel chan error)  {
// 	               panic("mock out the StartBackgroundUpdate method")
//             },
//         }
//
//         // use mockedHomepageClienter in code that requires Clienter
//         // and then make assertions.
//
//     }
type HomepageClienterMock struct {
	// AddNavigationCacheFunc mocks the AddNavigationCache method.
	AddNavigationCacheFunc func(ctx context.Context, updateInterval time.Duration) error

	// CloseFunc mocks the Close method.
	CloseFunc func()

	// GetHomePageFunc mocks the GetHomePage method.
	GetHomePageFunc func(ctx context.Context, userAccessToken string, collectionID string, lang string) (*model.HomepageData, error)

	// GetNavigationDataFunc mocks the GetNavigationData method.
	GetNavigationDataFunc func(ctx context.Context, lang string) (*models.Navigation, error)

	// StartBackgroundUpdateFunc mocks the StartBackgroundUpdate method.
	StartBackgroundUpdateFunc func(ctx context.Context, errorChannel chan error)

	// calls tracks calls to the methods.
	calls struct {
		// AddNavigationCache holds details about calls to the AddNavigationCache method.
		AddNavigationCache []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UpdateInterval is the updateInterval argument value.
			UpdateInterval time.Duration
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// GetHomePage holds details about calls to the GetHomePage method.
		GetHomePage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserAccessToken is the userAccessToken argument value.
			UserAccessToken string
			// CollectionID is the collectionID argument value.
			CollectionID string
			// Lang is the lang argument value.
			Lang string
		}
		// GetNavigationData holds details about calls to the GetNavigationData method.
		GetNavigationData []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Lang is the lang argument value.
			Lang string
		}
		// StartBackgroundUpdate holds details about calls to the StartBackgroundUpdate method.
		StartBackgroundUpdate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ErrorChannel is the errorChannel argument value.
			ErrorChannel chan error
		}
	}
}

// AddNavigationCache calls AddNavigationCacheFunc.
func (mock *HomepageClienterMock) AddNavigationCache(ctx context.Context, updateInterval time.Duration) error {
	if mock.AddNavigationCacheFunc == nil {
		panic("HomepageClienterMock.AddNavigationCacheFunc: method is nil but Clienter.AddNavigationCache was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		UpdateInterval time.Duration
	}{
		Ctx:            ctx,
		UpdateInterval: updateInterval,
	}
	lockHomepageClienterMockAddNavigationCache.Lock()
	mock.calls.AddNavigationCache = append(mock.calls.AddNavigationCache, callInfo)
	lockHomepageClienterMockAddNavigationCache.Unlock()
	return mock.AddNavigationCacheFunc(ctx, updateInterval)
}

// AddNavigationCacheCalls gets all the calls that were made to AddNavigationCache.
// Check the length with:
//     len(mockedHomepageClienter.AddNavigationCacheCalls())
func (mock *HomepageClienterMock) AddNavigationCacheCalls() []struct {
	Ctx            context.Context
	UpdateInterval time.Duration
} {
	var calls []struct {
		Ctx            context.Context
		UpdateInterval time.Duration
	}
	lockHomepageClienterMockAddNavigationCache.RLock()
	calls = mock.calls.AddNavigationCache
	lockHomepageClienterMockAddNavigationCache.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *HomepageClienterMock) Close() {
	if mock.CloseFunc == nil {
		panic("HomepageClienterMock.CloseFunc: method is nil but Clienter.Close was just called")
	}
	callInfo := struct {
	}{}
	lockHomepageClienterMockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	lockHomepageClienterMockClose.Unlock()
	mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//     len(mockedHomepageClienter.CloseCalls())
func (mock *HomepageClienterMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	lockHomepageClienterMockClose.RLock()
	calls = mock.calls.Close
	lockHomepageClienterMockClose.RUnlock()
	return calls
}

// GetHomePage calls GetHomePageFunc.
func (mock *HomepageClienterMock) GetHomePage(ctx context.Context, userAccessToken string, collectionID string, lang string) (*model.HomepageData, error) {
	if mock.GetHomePageFunc == nil {
		panic("HomepageClienterMock.GetHomePageFunc: method is nil but Clienter.GetHomePage was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		UserAccessToken string
		CollectionID    string
		Lang            string
	}{
		Ctx:             ctx,
		UserAccessToken: userAccessToken,
		CollectionID:    collectionID,
		Lang:            lang,
	}
	lockHomepageClienterMockGetHomePage.Lock()
	mock.calls.GetHomePage = append(mock.calls.GetHomePage, callInfo)
	lockHomepageClienterMockGetHomePage.Unlock()
	return mock.GetHomePageFunc(ctx, userAccessToken, collectionID, lang)
}

// GetHomePageCalls gets all the calls that were made to GetHomePage.
// Check the length with:
//     len(mockedHomepageClienter.GetHomePageCalls())
func (mock *HomepageClienterMock) GetHomePageCalls() []struct {
	Ctx             context.Context
	UserAccessToken string
	CollectionID    string
	Lang            string
} {
	var calls []struct {
		Ctx             context.Context
		UserAccessToken string
		CollectionID    string
		Lang            string
	}
	lockHomepageClienterMockGetHomePage.RLock()
	calls = mock.calls.GetHomePage
	lockHomepageClienterMockGetHomePage.RUnlock()
	return calls
}

// GetNavigationData calls GetNavigationDataFunc.
func (mock *HomepageClienterMock) GetNavigationData(ctx context.Context, lang string) (*models.Navigation, error) {
	if mock.GetNavigationDataFunc == nil {
		panic("HomepageClienterMock.GetNavigationDataFunc: method is nil but Clienter.GetNavigationData was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Lang string
	}{
		Ctx:  ctx,
		Lang: lang,
	}
	lockHomepageClienterMockGetNavigationData.Lock()
	mock.calls.GetNavigationData = append(mock.calls.GetNavigationData, callInfo)
	lockHomepageClienterMockGetNavigationData.Unlock()
	return mock.GetNavigationDataFunc(ctx, lang)
}

// GetNavigationDataCalls gets all the calls that were made to GetNavigationData.
// Check the length with:
//     len(mockedHomepageClienter.GetNavigationDataCalls())
func (mock *HomepageClienterMock) GetNavigationDataCalls() []struct {
	Ctx  context.Context
	Lang string
} {
	var calls []struct {
		Ctx  context.Context
		Lang string
	}
	lockHomepageClienterMockGetNavigationData.RLock()
	calls = mock.calls.GetNavigationData
	lockHomepageClienterMockGetNavigationData.RUnlock()
	return calls
}

// StartBackgroundUpdate calls StartBackgroundUpdateFunc.
func (mock *HomepageClienterMock) StartBackgroundUpdate(ctx context.Context, errorChannel chan error) {
	if mock.StartBackgroundUpdateFunc == nil {
		panic("HomepageClienterMock.StartBackgroundUpdateFunc: method is nil but Clienter.StartBackgroundUpdate was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ErrorChannel chan error
	}{
		Ctx:          ctx,
		ErrorChannel: errorChannel,
	}
	lockHomepageClienterMockStartBackgroundUpdate.Lock()
	mock.calls.StartBackgroundUpdate = append(mock.calls.StartBackgroundUpdate, callInfo)
	lockHomepageClienterMockStartBackgroundUpdate.Unlock()
	mock.StartBackgroundUpdateFunc(ctx, errorChannel)
}

// StartBackgroundUpdateCalls gets all the calls that were made to StartBackgroundUpdate.
// Check the length with:
//     len(mockedHomepageClienter.StartBackgroundUpdateCalls())
func (mock *HomepageClienterMock) StartBackgroundUpdateCalls() []struct {
	Ctx          context.Context
	ErrorChannel chan error
} {
	var calls []struct {
		Ctx          context.Context
		ErrorChannel chan error
	}
	lockHomepageClienterMockStartBackgroundUpdate.RLock()
	calls = mock.calls.StartBackgroundUpdate
	lockHomepageClienterMockStartBackgroundUpdate.RUnlock()
	return calls
}
