---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.9-bookworm

inputs:
  - name: dp-frontend-homepage-controller

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-frontend-homepage-controller/ci/scripts/build.sh
